package pl.ptaszek.opole.model;

public enum TypObciazenia {

	SLUZEBNOSC_PRZESYLU, 
	SLUZEBNOSC_GRUNTOWA, 
	SLUZEBNOSC_PRZECHODU,
	UZYTKOWANIE, 
	UZYTKOWANIE_WIECZYSTE, 
	UZYCZENIE, 
	NAJEM, 
	DZIERZAWA,
	DOZYWOCIE,
	TRWALY_ZARZAD;
}
